plugins/hackernews.py
Simple regex and api call for retrieving info on comments and stories
=> Added support for retrieving information from hackernews urls

plugins/weather.py
This fixes two word place names, like 'Las Vegas, Nevada'
=> weather: change location quoting mechanism

plugins/mtg.py
Made it so .mtg pulls from an api instead of screen scraping
=> fixed mtg plugin

plugins/mtg.py
The rstrip on the text result may fix the issue where planeswalkers don't get printed, but maybe not. Mostly just changes the formatting to print results that look good to me.
=> Changed output formatting of mtg

plugins/mtg.py
1) Symbol support for tap, untap, colorless mana, snow mana, phyrexian mana
2) Newline support for planeswalkers and other cards that were malformed with multiple lines
3) Just a little prettier overall formatting of the output
4) Valid card edition detection so links to the website always actually show the card
=> Symbol support and more for MTG

plugins/weather.py
The query Edmonton, AB, Canada was causing problems. The API expects state/city for US locations, but for non-US locations it wants country/city. 
Tested with:
Edmonton, AB, Canada
Montreal, Canada
Las Vegas, Nevada
80031
=> weather: Try to handle city state country queries

plugins/mtg.py
Now prints critical information that was requested (power/toughness, types as printed).
=> Updates on mtg formatting

plugins/tag.py
=> .tag foo & bar wont intersect mixed case tagged nicks

plugins/bitcoin.py
=> add .ethereum

plugins/remember.py
hello! this lets you do `?word 2` to retrieve page 2 of the remember for `word`. no more remembers lost to the character limit! namaste
=> add basic pagination to remembers

plugins/bitcoin.py
=> fix bit/eth: swap to bitstamp API

plugins/crypto.py
Can look up any of the thousands of new crypto coins and returns some cool info including the same things that .bit and .eth return
=> Added generic crypto plugin

plugins/stock.py
Uses "free" robinhood quote api endpoint. (free as in this is what they use on their mobile app and dont seem to care that other people hit it -- no api key required)
=> Re-write stock plugin to use robinhood.com api

plugins/metacritic.py
scraping metacritic was failing because classes changed and
some data is now missing
=> update metacritic for new HTML

plugins/imdb.py
Seems like omdbapi needs an API key now, so this adds the ability
to inject one through the configuration
=> support API key for omdbapi

plugins/stock.py
The color code was getting merged with non-negative price changes.
=> stock: fix colors.

plugins/rottentomatoes.py
it seems like rottentomatoes has removed the public free API
which allows non-corporate entities.  Instead, only businesses
with "good" reasons that the owner of RT, fandango, likes can
sign up to use the API
this change updates the rottentomatoes plugin to hit the RT site
directly and pull data from that
=> skip rottentomatoes API and hit site directly

plugins/pre.py
most of the predb sites seem to be using a very strict
cloudflare setting, so we can't scrap them.  PR3.us doesn't
but is definitely a bit on the weirder side to try to scrape.
if the accept headers are missing it seems to crash with the
underlying PHP, but at least it gives us the same data back as
with the other predb
=> switch to another predb because orlydb is down

plugins/dice.py
in the example 2d20-d5+4 the outhput was incorrect because4 the output was 10 because it
the plugin parsed it as "2D20" + "1D5" + "4"parsed it as "2D20" + "1D5" + "4"
instead, it needs to be parsed as "2D20" + "-1D5" + "4"
=> fix subtraction in dice plugin

plugins/weather.py
IBM is shutting the wunderground API down, so use google geocoding api + darksky instead.
This depends on #205, and fixes #136 most likely
=> Use darksky for the weather plugin

.travis.yml
If you have a travis account connected to your repo it should start running the tests.
[![Build Status](https://travis-ci.com/imnotjames/skybot.svg?branch=master)](https://travis-ci.com/imnotjames/skybot)
Then you can get a nifty badge and notifications when the build is broken.
=> add travis config for automating tests

README.md
All the docs are in markdown, or so it seems.  The readme probably should be too.
=> Use markdown for readme

plugins/eval.py
This is kinda hacky and theres probably a better way to do polling, suggestions welcomed.
=> Add eval plugin based on judge0 API

plugins/tarot.py
My boss @Ell was getting on me to finish this so I did. 
I haven't really had a chance to test it but the code looks sound esp. as it's a relatively simple api and I'm approaching it simply.
=> Add support for tarot things

plugins/tarot.py
=> Update .tarot and .fortune commands to actually work

plugins/tarot.py
=> Elgruntox this up

plugins/google.py
=> Additional prompts for GIS command

plugins/weather.py
plug in, free (10k req/mo) replacement for opensky
https://pirate-weather.apiable.io/
=> changed weather api to pirateweather

plugins/mastodon.py
Just like the twitter plugin, this plugin watches for links to mastodon toots and prints their text.
=> add plugin for mastodon toots
